language: generic

sudo: required
services:
 - docker

before_install:
 - docker build -t  tYigitYilmaz/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true tYigitYilmaz/docker-react npm run test